spring.application.name=agendApp
server.port=8081


## Conexión a la DB
spring.datasource.url=jdbc:mysql://localhost:3306/agendApp?createDatabaseIfNotExist=true
spring.datasource.username=root

# Credenciales produccion
spring.datasource.password=wacaballa

## COnfiguración extra de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql=true

## JPA
## spring.jpa.hibernate.ddl-auto=none
# spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
## spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.hibernate.ddl-auto=validate

# True en produccion
spring.thymeleaf.cache=true

## Folder photos
app.upload.dir=uploads/profiles

# --- SPRING BOOT ---
spring.servlet.multipart.enabled=true
# spring.servlet.multipart.max-file-size=50MB
# spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB

# --- TOMCAT ---
# server.tomcat.max-swallow-size=52428800
# server.tomcat.max-http-form-post-size=52428800
# server.tomcat.max-post-size=52428800
server.tomcat.max-swallow-size=104857600
server.tomcat.max-http-form-post-size=104857600
server.tomcat.max-post-size=104857600
server.tomcat.max-part-count=50
server.tomcat.connection-timeout=20000
server.tomcat.threads.max=400
server.tomcat.threads.min-spare=10

# Aumentar buffer de Tomcat
server.tomcat.accept-count=100

## Notificaciones por email a profesionales
## Completá estas credenciales para activar el envío automático de correos.
## Ejemplo SMTP con TLS:
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=odontologia.alvear856@gmail.com
spring.mail.password=okjnooyphhrzqbxd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=odontologia.alvear856@gmail.com